// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package dbgen

import (
	"context"
	"time"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (user_id, name, prompt, keywords, sources, region, frequency, is_one_time, is_active, status, next_run_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1, 'pending', ?)
RETURNING id, user_id, name, prompt, keywords, sources, region, frequency, is_one_time, is_active, last_run_at, next_run_at, status, created_at, updated_at, current_conversation_id
`

type CreateJobParams struct {
	UserID    int64      `json:"user_id"`
	Name      string     `json:"name"`
	Prompt    string     `json:"prompt"`
	Keywords  string     `json:"keywords"`
	Sources   string     `json:"sources"`
	Region    string     `json:"region"`
	Frequency string     `json:"frequency"`
	IsOneTime int64      `json:"is_one_time"`
	NextRunAt *time.Time `json:"next_run_at"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.UserID,
		arg.Name,
		arg.Prompt,
		arg.Keywords,
		arg.Sources,
		arg.Region,
		arg.Frequency,
		arg.IsOneTime,
		arg.NextRunAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prompt,
		&i.Keywords,
		&i.Sources,
		&i.Region,
		&i.Frequency,
		&i.IsOneTime,
		&i.IsActive,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentConversationID,
	)
	return i, err
}

const deleteJob = `-- name: DeleteJob :exec
DELETE FROM jobs WHERE id = ? AND user_id = ?
`

type DeleteJobParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteJob(ctx context.Context, arg DeleteJobParams) error {
	_, err := q.db.ExecContext(ctx, deleteJob, arg.ID, arg.UserID)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, user_id, name, prompt, keywords, sources, region, frequency, is_one_time, is_active, last_run_at, next_run_at, status, created_at, updated_at, current_conversation_id FROM jobs WHERE id = ? AND user_id = ?
`

type GetJobParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetJob(ctx context.Context, arg GetJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, arg.ID, arg.UserID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prompt,
		&i.Keywords,
		&i.Sources,
		&i.Region,
		&i.Frequency,
		&i.IsOneTime,
		&i.IsActive,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentConversationID,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, user_id, name, prompt, keywords, sources, region, frequency, is_one_time, is_active, last_run_at, next_run_at, status, created_at, updated_at, current_conversation_id FROM jobs WHERE id = ?
`

func (q *Queries) GetJobByID(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prompt,
		&i.Keywords,
		&i.Sources,
		&i.Region,
		&i.Frequency,
		&i.IsOneTime,
		&i.IsActive,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrentConversationID,
	)
	return i, err
}

const listActiveJobs = `-- name: ListActiveJobs :many
SELECT id, user_id, name, prompt, keywords, sources, region, frequency, is_one_time, is_active, last_run_at, next_run_at, status, created_at, updated_at, current_conversation_id FROM jobs WHERE is_active = 1 AND (is_one_time = 0 OR status = 'pending')
`

func (q *Queries) ListActiveJobs(ctx context.Context) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listActiveJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prompt,
			&i.Keywords,
			&i.Sources,
			&i.Region,
			&i.Frequency,
			&i.IsOneTime,
			&i.IsActive,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentConversationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByUser = `-- name: ListJobsByUser :many
SELECT id, user_id, name, prompt, keywords, sources, region, frequency, is_one_time, is_active, last_run_at, next_run_at, status, created_at, updated_at, current_conversation_id FROM jobs WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListJobsByUser(ctx context.Context, userID int64) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prompt,
			&i.Keywords,
			&i.Sources,
			&i.Region,
			&i.Frequency,
			&i.IsOneTime,
			&i.IsActive,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentConversationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :exec
UPDATE jobs
SET name = ?, prompt = ?, keywords = ?, sources = ?, region = ?, frequency = ?, is_active = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ?
`

type UpdateJobParams struct {
	Name      string `json:"name"`
	Prompt    string `json:"prompt"`
	Keywords  string `json:"keywords"`
	Sources   string `json:"sources"`
	Region    string `json:"region"`
	Frequency string `json:"frequency"`
	IsActive  int64  `json:"is_active"`
	ID        int64  `json:"id"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) error {
	_, err := q.db.ExecContext(ctx, updateJob,
		arg.Name,
		arg.Prompt,
		arg.Keywords,
		arg.Sources,
		arg.Region,
		arg.Frequency,
		arg.IsActive,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs
SET status = ?, last_run_at = ?, next_run_at = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateJobStatusParams struct {
	Status    string     `json:"status"`
	LastRunAt *time.Time `json:"last_run_at"`
	NextRunAt *time.Time `json:"next_run_at"`
	ID        int64      `json:"id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJobStatus,
		arg.Status,
		arg.LastRunAt,
		arg.NextRunAt,
		arg.ID,
	)
	return err
}
