// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type Article struct {
	ID          int64     `json:"id"`
	JobID       int64     `json:"job_id"`
	UserID      int64     `json:"user_id"`
	Title       string    `json:"title"`
	Url         string    `json:"url"`
	Summary     string    `json:"summary"`
	ContentPath string    `json:"content_path"`
	RetrievedAt time.Time `json:"retrieved_at"`
}

type Job struct {
	ID                    int64      `json:"id"`
	UserID                int64      `json:"user_id"`
	Name                  string     `json:"name"`
	Prompt                string     `json:"prompt"`
	Keywords              string     `json:"keywords"`
	Sources               string     `json:"sources"`
	Region                string     `json:"region"`
	Frequency             string     `json:"frequency"`
	IsOneTime             int64      `json:"is_one_time"`
	IsActive              int64      `json:"is_active"`
	LastRunAt             *time.Time `json:"last_run_at"`
	NextRunAt             *time.Time `json:"next_run_at"`
	Status                string     `json:"status"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
	CurrentConversationID *string    `json:"current_conversation_id"`
}

type JobRun struct {
	ID                int64      `json:"id"`
	JobID             int64      `json:"job_id"`
	Status            string     `json:"status"`
	ErrorMessage      *string    `json:"error_message"`
	StartedAt         time.Time  `json:"started_at"`
	CompletedAt       *time.Time `json:"completed_at"`
	ArticlesSaved     *int64     `json:"articles_saved"`
	DuplicatesSkipped *int64     `json:"duplicates_skipped"`
	LogPath           string     `json:"log_path"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type Preference struct {
	ID             int64     `json:"id"`
	UserID         int64     `json:"user_id"`
	SystemPrompt   string    `json:"system_prompt"`
	DiscordWebhook string    `json:"discord_webhook"`
	NotifySuccess  int64     `json:"notify_success"`
	NotifyFailure  int64     `json:"notify_failure"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type User struct {
	ID        int64     `json:"id"`
	ExeUserID string    `json:"exe_user_id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
