// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: preferences.sql

package dbgen

import (
	"context"
)

const createPreferences = `-- name: CreatePreferences :one
INSERT INTO preferences (user_id, system_prompt, discord_webhook, notify_success, notify_failure)
VALUES (?, '', '', 0, 0)
RETURNING id, user_id, system_prompt, discord_webhook, notify_success, notify_failure, created_at, updated_at
`

func (q *Queries) CreatePreferences(ctx context.Context, userID int64) (Preference, error) {
	row := q.db.QueryRowContext(ctx, createPreferences, userID)
	var i Preference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SystemPrompt,
		&i.DiscordWebhook,
		&i.NotifySuccess,
		&i.NotifyFailure,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPreferences = `-- name: GetPreferences :one
SELECT id, user_id, system_prompt, discord_webhook, notify_success, notify_failure, created_at, updated_at FROM preferences WHERE user_id = ?
`

func (q *Queries) GetPreferences(ctx context.Context, userID int64) (Preference, error) {
	row := q.db.QueryRowContext(ctx, getPreferences, userID)
	var i Preference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SystemPrompt,
		&i.DiscordWebhook,
		&i.NotifySuccess,
		&i.NotifyFailure,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePreferences = `-- name: UpdatePreferences :exec
UPDATE preferences 
SET system_prompt = ?, discord_webhook = ?, notify_success = ?, notify_failure = ?, updated_at = CURRENT_TIMESTAMP
WHERE user_id = ?
`

type UpdatePreferencesParams struct {
	SystemPrompt   string `json:"system_prompt"`
	DiscordWebhook string `json:"discord_webhook"`
	NotifySuccess  int64  `json:"notify_success"`
	NotifyFailure  int64  `json:"notify_failure"`
	UserID         int64  `json:"user_id"`
}

func (q *Queries) UpdatePreferences(ctx context.Context, arg UpdatePreferencesParams) error {
	_, err := q.db.ExecContext(ctx, updatePreferences,
		arg.SystemPrompt,
		arg.DiscordWebhook,
		arg.NotifySuccess,
		arg.NotifyFailure,
		arg.UserID,
	)
	return err
}
