// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package dbgen

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (exe_user_id, email, created_at, updated_at)
VALUES (?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, exe_user_id, email, created_at, updated_at
`

type CreateUserParams struct {
	ExeUserID string `json:"exe_user_id"`
	Email     string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ExeUserID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExeUserID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByExeID = `-- name: GetUserByExeID :one
SELECT id, exe_user_id, email, created_at, updated_at FROM users WHERE exe_user_id = ?
`

func (q *Queries) GetUserByExeID(ctx context.Context, exeUserID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByExeID, exeUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExeUserID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users SET email = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateUserEmailParams struct {
	Email string `json:"email"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateUserEmail, arg.Email, arg.ID)
	return err
}
